### ISSUE TITLE
[BUG] White list of files

### ISSUE THREAD

**Issue by BakasuraRCE** [Carve/qbittorrent-webui-cjratliff.com#3]
Hi,

When you review the list of files in a torrent, there are clear lines interspersed.

![image](https://user-images.githubusercontent.com/26231582/224846136-1ef31666-1707-4efe-9ee3-dc07c96298f9.png)

Best regards.

**Comment by Carve** [comment]
Fixed in commit: [86e8fce](https://github.com/Carve/qbittorrent-webui-cjratliff.com/commit/86e8fce6cffaae1c04bdfa47cfef2ab956cac30c)

**Comment by BakasuraRCE** [comment]
@Carve  still getting the error hehe, check this image:

![image](https://user-images.githubusercontent.com/26231582/224870077-3d96b272-fe7e-461d-b90c-29c168d6c762.png)

**Comment by Carve** [comment]
> @Carve still getting the error hehe, check this image:
> 
> ![image](https://user-images.githubusercontent.com/26231582/224870077-3d96b272-fe7e-461d-b90c-29c168d6c762.png)

Have you tried clearing your cache?

![image](https://user-images.githubusercontent.com/662856/224870512-9e5d23de-2ae5-4ff7-b122-0d2be85fdd7d.png)

**Comment by BakasuraRCE** [comment]
Yes, but I suspect that the difference in file loading order between your browser and mine is due to http/2 or the browser itself. It's possible that it's ignoring the order in which the HTML is calling them.

**Comment by BakasuraRCE** [comment]
I can confirm that it happend only in my Firefox, in Chorme is OK.

**Comment by Carve** [comment]
> I can confirm that it happend only in my Firefox, in Chorme is OK.

![image](https://user-images.githubusercontent.com/662856/224871304-7a915e06-1533-4a51-8302-ab01b8d3345d.png)
